// Code generated by cmd/permgen from a bundled OpenAPI document; DO NOT EDIT.
package main

// Vocabulary is the permission codename universe: one entry per
// operation plus every root x-permissions capability.
var Vocabulary = []string{
	"assignRole",
	"completeTask",
	"createProject",
	"createRole",
	"createTask",
	"deleteProject",
	"getProject",
	"health",
	"listProjects",
	"listRoles",
	"listTasks",
	"setRolePermission",
}

// RoutePermissions maps "METHOD /path" to its governing codename.
// Every non-public operation appears here; the middleware denies a
// matched route that is in neither this map nor PublicRoutes.
var RoutePermissions = map[string]string{
	"DELETE /projects/{id}":               "deleteProject",
	"GET /projects":                       "listProjects",
	"GET /projects/{id}":                  "getProject",
	"GET /projects/{id}/tasks":            "listTasks",
	"GET /roles":                          "listRoles",
	"POST /members/{userId}/roles/{slug}": "assignRole",
	"POST /projects":                      "createProject",
	"POST /projects/{id}/tasks":           "createTask",
	"POST /roles":                         "createRole",
	"POST /roles/{slug}/permissions":      "setRolePermission",
	"POST /tasks/{id}/complete":           "completeTask",
}

// PublicRoutes is the explicit no-auth allowlist: every operation marked
// x-public. Absence from RoutePermissions is not enough to be public.
var PublicRoutes = map[string]bool{
	"GET /health": true,
}

// RoleSeed is the slug -> codenames matrix from x-role-seed.
var RoleSeed = map[string][]string{
	"editor": {
		"completeTask",
		"createProject",
		"createTask",
		"getProject",
		"listProjects",
		"listRoles",
		"listTasks",
	},
	"member": {
		"getProject",
		"listProjects",
		"listRoles",
		"listTasks",
	},
}
