// Copyright 2026 The authz Authors.
// SPDX-License-Identifier: Apache-2.0

// Command permgen derives authorization artifacts from a bundled OpenAPI
// document, so the spec stays the single source of truth (zero hand-written
// permission lists):
//
//   - Vocabulary       — every codename: one per operationId, plus any
//     non-endpoint capability listed under the root
//     extension `x-permissions`.
//   - RoutePermissions — "METHOD /path" → codename, for middleware
//     enforcement.
//   - PublicRoutes     — the explicit no-auth allowlist: "METHOD /path"
//     for every operation marked `x-public: true`. The
//     middleware denies any matched route absent from
//     both maps, so public access is declared, never
//     inferred from a missing policy.
//   - RoleSeed         — role slug → codenames, from the optional root
//     extension `x-role-seed` (host-defined matrix).
//
// The output is a deterministic, gofmt-clean Go file.
//
//	go run ./cmd/permgen -spec example/openapi.json -out example/perm_gen.go -package main
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

type operation struct {
	Method      string
	Path        string
	OperationID string
	Public      bool
}

type spec struct {
	Paths map[string]map[string]struct {
		OperationID string `json:"operationId"`
		XPublic     bool   `json:"x-public"`
	} `json:"paths"`
	XPermissions []string            `json:"x-permissions"`
	XRoleSeed    map[string][]string `json:"x-role-seed"`
}

// generate renders the Go source for a bundled OpenAPI document.
func generate(specJSON []byte, pkg string) ([]byte, error) {
	var s spec
	if err := json.Unmarshal(specJSON, &s); err != nil {
		return nil, fmt.Errorf("parse spec: %w", err)
	}

	vocab := map[string]bool{}
	public := map[string]bool{}
	var ops []operation
	for path, methods := range s.Paths {
		for method, o := range methods {
			switch method {
			case "get", "post", "put", "patch", "delete":
				if o.OperationID == "" {
					return nil, fmt.Errorf("%s %s: operationId is required", strings.ToUpper(method), path)
				}
			case "head", "options", "trace":
				return nil, fmt.Errorf("%s %s: method is not part of the vocabulary; remove it or use get/post/put/patch/delete", strings.ToUpper(method), path)
			default:
				// Path-item fields (parameters, summary, servers, $ref) and
				// an uppercase method key. An uppercase method would be
				// silently skipped, so refuse it.
				if looksLikeMethod(method) {
					return nil, fmt.Errorf("%s %s: method must be lowercase get, post, put, patch, or delete", method, path)
				}
				continue
			}
			vocab[o.OperationID] = true
			if o.XPublic {
				// Public: no middleware codename, but recorded explicitly so
				// the middleware can tell a declared public route apart from
				// an unlisted (misconfigured) one.
				public[strings.ToUpper(method)+" "+path] = true
				continue
			}
			ops = append(ops, operation{method, path, o.OperationID, o.XPublic})
		}
	}
	for _, p := range s.XPermissions {
		vocab[p] = true
	}

	routes := map[string]string{}
	for _, o := range ops {
		routes[strings.ToUpper(o.Method)+" "+o.Path] = o.OperationID
	}

	seed := map[string][]string{}
	for slug, codenames := range s.XRoleSeed {
		c := append([]string(nil), codenames...)
		sort.Strings(c)
		seed[slug] = c
	}

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by cmd/permgen from a bundled OpenAPI document; DO NOT EDIT.")
	fmt.Fprintf(&b, "package %s\n\n", pkg)

	fmt.Fprintln(&b, "// Vocabulary is the permission codename universe: one entry per")
	fmt.Fprintln(&b, "// operation plus every root x-permissions capability.")
	fmt.Fprintln(&b, "var Vocabulary = []string{")
	for _, c := range sortedKeys(vocab) {
		fmt.Fprintf(&b, "\t%q,\n", c)
	}
	fmt.Fprintln(&b, "}")

	fmt.Fprintln(&b, "\n// RoutePermissions maps \"METHOD /path\" to its governing codename.")
	fmt.Fprintln(&b, "// Every non-public operation appears here; the middleware denies a")
	fmt.Fprintln(&b, "// matched route that is in neither this map nor PublicRoutes.")
	fmt.Fprintln(&b, "var RoutePermissions = map[string]string{")
	for _, k := range sortedKeys(routes) {
		fmt.Fprintf(&b, "\t%q: %q,\n", k, routes[k])
	}
	fmt.Fprintln(&b, "}")

	fmt.Fprintln(&b, "\n// PublicRoutes is the explicit no-auth allowlist: every operation marked")
	fmt.Fprintln(&b, "// x-public. Absence from RoutePermissions is not enough to be public.")
	fmt.Fprintln(&b, "var PublicRoutes = map[string]bool{")
	for _, k := range sortedKeys(public) {
		fmt.Fprintf(&b, "\t%q: true,\n", k)
	}
	fmt.Fprintln(&b, "}")

	fmt.Fprintln(&b, "\n// RoleSeed is the slug -> codenames matrix from x-role-seed.")
	fmt.Fprintln(&b, "var RoleSeed = map[string][]string{")
	for _, slug := range sortedKeys(seed) {
		fmt.Fprintf(&b, "\t%q: {\n", slug)
		for _, c := range seed[slug] {
			fmt.Fprintf(&b, "\t\t%q,\n", c)
		}
		fmt.Fprintln(&b, "\t},")
	}
	fmt.Fprintln(&b, "}")

	return format.Source(b.Bytes())
}

// seedJSON renders the RoleSeed as a JSON object for seed_role_permissions().
func seedJSON(seed map[string][]string) ([]byte, error) {
	// Stable key order is provided by json.Marshal for map[string][]string?
	// No — encoding/json sorts map keys, so output is deterministic.
	return json.Marshal(seed)
}

func main() {
	var (
		specPath = flag.String("spec", "openapi.json", "path to the bundled OpenAPI JSON document")
		outPath  = flag.String("out", "perm_gen.go", "output Go file (\"-\" for stdout)")
		pkg      = flag.String("package", "main", "package name for the generated file")
		seedOut  = flag.String("seed-out", "", "optional path to write the role seed as JSON")
	)
	flag.Parse()

	raw, err := os.ReadFile(*specPath)
	if err != nil {
		fail(err)
	}
	src, err := generate(raw, *pkg)
	if err != nil {
		fail(err)
	}
	if *outPath == "-" {
		_, _ = os.Stdout.Write(src)
	} else if err := os.WriteFile(*outPath, src, 0o644); err != nil {
		fail(err)
	}

	if *seedOut != "" {
		var s spec
		if err := json.Unmarshal(raw, &s); err != nil {
			fail(err)
		}
		j, err := seedJSON(s.XRoleSeed)
		if err != nil {
			fail(err)
		}
		if err := os.WriteFile(*seedOut, j, 0o644); err != nil {
			fail(err)
		}
	}
	fmt.Fprintf(os.Stderr, "permgen: wrote %s\n", *outPath)
}

func looksLikeMethod(method string) bool {
	switch strings.ToLower(method) {
	case "get", "post", "put", "patch", "delete", "head", "options", "trace":
		return method != strings.ToLower(method)
	default:
		return false
	}
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func fail(err error) {
	fmt.Fprintf(os.Stderr, "permgen: %v\n", err)
	os.Exit(1)
}
